# mappings/normalizer/ocsf/1.7.0/osquery/routing.yaml
format_version: 1

routing:
  provider: null
  channel: null

routes:
  - route_id: process_events
    match:
      query_names: [process_events]
    class_map: classes/process_activity_1007.yaml

  - route_id: file_events
    match:
      query_names: [file_events]
    class_map: classes/file_system_activity_1001.yaml

  - route_id: socket_events
    match:
      query_names: [socket_events]
    class_map: classes/network_activity_4001.yaml
