# mappings/normalizer/ocsf/1.7.0/windows-sysmon/routing.yaml
format_version: 1

routing:
  provider: Microsoft-Windows-Sysmon
  channel: Microsoft-Windows-Sysmon/Operational

routes:
  - route_id: sysmon_process_activity
    match:
      event_ids: [1, 5]
    class_map: classes/process_activity_1007.yaml
  - route_id: sysmon_network_activity
    match:
      event_ids: [3]
    class_map: classes/network_activity_4001.yaml
  - route_id: sysmon_file_system_activity
    match:
      event_ids: [11]
    class_map: classes/file_system_activity_1001.yaml
  - route_id: sysmon_dns_activity
    match:
      event_ids: [22]
    class_map: classes/dns_activity_4003.yaml
